### ISSUE TITLE
Ebook dead links inserted in HTML

### ISSUE THREAD

**Issue by kelson42** [kiwix/gutenberg#31]
If a book has for example a PDF version, but for any reason the ebook is not available in the dl-cache/static directory, then the HTML still includes it. To avoid any dead link this should not be the case.

An example:
With our current code (dcefb5f52eaef5a025c97ce8a1d89b9e10e098b0), for the following book, the PDF is not downloaded and consequently not available, but the HTML generated still provides links/icons pointing to the PDF version. All these links are dead links and should not be inserted.
http://www.gutenberg.org/ebooks/11

**Comment by rgaudin** [comment]
Was a download issue. Fixed along with #32.
