### ISSUE TITLE
Dead links in HTML ebooks

### ISSUE THREAD

**Issue by kelson42** [kiwix/gutenberg#34]
In "Adventures of Huckleberry Finn" (#76), the HTML version of the book has a box/div "Format Choice" a the top of the page.

In that box, the second link with the label "2. A file with images which automatically accomodate to any screen size; this is the best choice for the small screens of Tablets and Smart Phones." is a dead link.

On the online version this link is not dead:
http://www.gutenberg.org/files/76/76-h/76-h.htm

**Comment by rgaudin** [comment]
Can not reproduce.
Can you check whether this box is still on the online version?
