### ISSUE TITLE
Dead links in HTML ebooks (second use case)

### ISSUE THREAD

**Issue by kelson42** [kiwix/gutenberg#35]
In "Les Misérables" #135, at the top of the page you have an "Enlarge" link inviting I guess to see the picture beside (photography of books) in a better resolution. Unfortunately this is a dead link, the picture does not exist.

On the online version, the picture is there:
http://www.gutenberg.org/files/135/135-h/135-h.htm

**Comment by rgaudin** [comment]
At the moment, the script is now rewriting any link but the internal (anchor) ones (using `#`).
That would be an enhancement request.
